#!/bin/sh

module="bchd"
device="bchd"
mode="664"

# Group: since distributions do it differently, look for wheel or use sudo
if grep -q '^sudo:' /etc/group; then
    group="sudo"
else
    group="wheel"
fi

# invoke insmod with all arguments we got
# and use a pathname, as insmod doesn't look in . by default
insmod ./$module.ko $* || exit 1

# retrieve major number
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

# Remove stale nodes and replace them, then give gid and perms

rm -f /dev/${device}
mknod /dev/${device} c $major 0
#ln -sf ${device} /dev/${device}
chgrp $group /dev/${device} 
chmod $mode  /dev/${device}
